### ISSUE TITLE
Question: Can your component be used in Classic ?

### ISSUE THREAD

**Issue by annemarieYodle** [douglascayers/sfdc-related-files-lightning#10]
Can they be used in Visualforce pages with Lightning Out?
 I don't know much about how that works, but am looking for a solution for our users which we have not migrated to lightning.

Thanks for all your great work!

Anne-Marie

**Comment by DouglasCAyers** [comment]
Yes, I'll see what I can whip together this weekend. Lightning Out would be used to expose this component in Visualforce.

**Comment by annemarieYodle** [comment]
You are the best!!  Thank you so much!

**Comment by DouglasCAyers** [comment]
@annemarieYodle I just developed this feature in the **develop** branch of the code, will be available in the next release. Thanks for your patience

**Comment by annemarieYodle** [comment]
Thanks so much, Doug!!

**Comment by DouglasCAyers** [comment]
@annemarieYodle Sorry for the delay, but I'm unable to create a new version of the app until Spring 18 release due to this known issue: https://success.salesforce.com/issues_view?id=a1p3A000000EQJzQAO

**Comment by annemarieYodle** [comment]
Thanks for the update, Doug.  I do appreciate your work on this!  Just released the lightning version last week.  :)

**Comment by futureassst** [comment]
Hey @DouglasCAyers 

Is the classic version now available? Wanting to make the switch but without classic support for this feature it won't be doable as we are only in early days of select pilot users for lightning.

Also I checked out the lightning component which looks great but we need an 'All' button at the top of the object list so that we can see a complete historical track of attachments from the account and all related objects (not just one object at a time) just like it does with the notes & attachments. Is this possible?

**Comment by DouglasCAyers** [comment]
Hi @MichaelFutureAssist,

Technically speaking, the blocking bug has been fixed on the Salesforce platform so hypothetically I should be able to release the version support for Classic. I just haven't had the time to do those last few steps to package it up and release it.

Regarding an 'All' button to show all files or notes rather than filtered by related object, that I don't believe can be done without major performance issues. Due to system limitations in how we can query for files and notes is what led to the design to be how it is today. Not ideal, but better than nothing for some folks.

**Comment by MichaelFutureAssist** [comment]
Thanks for the update Doug.

I will eagerly wait for when you have time to add it to release it, it is critically affecting some of the adoption for a few champion users (I can't turn on the new notes without a solution for the classic users)
