### ISSUE TITLE
Field bar overlaps component frame

### ISSUE THREAD

**Issue by DylanKent** [douglascayers/sfdc-related-files-lightning#12]
Hi Doug,

Installed this component today, it's great and very helpful, however I noticed a display issue, though I'm not sure if it's just me, where the fields bar overlaps the component frame, I have attached a screenshot.

Kind Regards,
Dylan

![overlap](https://user-images.githubusercontent.com/33833742/33019541-1b17a89a-cdfb-11e7-93e1-5cc22ecc003e.PNG)

**Comment by DouglasCAyers** [comment]
Thanks @DylanKent. Looks like a CSS issue, will take a look to get corrected.

**Comment by DouglasCAyers** [comment]
Hi @DylanKent,

I've not been able to reproduce the problem in IE11, Microsoft Edge, or Google Chrome.

* What OS and browser are you using?
* Are there any other components on the page other than the two shown in your screenshot? 
* What page layout are you using?
* Does this happen on every object page you try or just a sepcific one?

Thanks

**Comment by JulianneNashSmith** [comment]
Hi @DouglasCAyers ,
This is possibly a slightly different issue, but related to the one above. I have a few suggestions about how this Related Files list could look better when it's placed into a tab on a lightning record page. See screenshot below. 
![2018-01-11_14-39-14](https://user-images.githubusercontent.com/35320621/34807646-111674d2-f6de-11e7-82e1-4fa603d90a49.jpg)

**Comment by JulianneNashSmith** [comment]
Hi @DouglasCAyers 

I've been able to reproduce the problem reported by @DylanKent in Google Chrome and Internet Explorer 11. It happens when you insert the Related Files component onto the lightning record page underneath a set of tabs, instead of actually on one of the tab pages. Here's an example, as you see it in the Lightning App Builder in Google Chrome:
![2018-01-11_15-19-36](https://user-images.githubusercontent.com/35320621/34808409-ef140e1c-f6e2-11e7-99a1-a5ac1be2b5f7.jpg)
And here's an example of how that page renders in Internet Explorer:
![2018-01-11_15-21-53](https://user-images.githubusercontent.com/35320621/34808461-368524d4-f6e3-11e7-9e12-37a32547d071.jpg)

**Comment by DouglasCAyers** [comment]
Hi @JulianneNashSmith,

Thanks for the detailed feedback and steps to reproduce the issue.

Adding the outline and bolding the title should be easy cosmetic changes. I'll have to dig into what's conflicting on the CSS side that causes the table to extend wide like that.

**Comment by unclejieves** [comment]
Wanted to note I've installed the component and its working well in that is providing invaluable visibility to related files under an Account...but also running into the same overflow issue as noted above.

**Comment by douglascayers** [comment]
Hi @unclejieves, thanks for the kind feedback.

I'm long over due to make some updates to this project. I'll see what I can accomplish this week.

Thanks

**Comment by douglascayers** [comment]
I'm working on updates to the styling for the next release of this app.

Here's a screen shot to show the improvements:

![image](https://user-images.githubusercontent.com/4142577/57978737-522ba680-79d8-11e9-9a40-cde595ca21ae.png)
