### ISSUE TITLE
Relates Files includes ContentNote records

### ISSUE THREAD

**Issue by steinstv** [douglascayers/sfdc-related-files-lightning#14]
Hi @DouglasCAyers  - We have a custom object that is M:D to Account.  I have added your configured to the Account page and it correctly displays Files related to the custom object.... but the list also include Notes related to the custom object in the list of related Files.
Is it possible to suppress Notes or to specify them explicitly?
Thanks!

**Comment by DouglasCAyers** [comment]
Hi @steinstv,

Good catch. Both Files and Notes store their version history in the ContentVerison object (which is what I'm querying) and so the both are being mixed as you observed.

I should be able to filter by the file type to exclude `.snote` so that the notes are excluded (or included) based on preference.

Thanks

**Comment by douglascayers** [comment]
In the next release you'll be able to filter the component to include Files, Notes, or both.

![image](https://user-images.githubusercontent.com/4142577/57979705-2d8afb00-79e7-11e9-8566-a56016af6e76.png)
