### ISSUE TITLE
Files related to the Account

### ISSUE THREAD

**Issue by MukeshKatochsfdc** [douglascayers/sfdc-related-files-lightning#23]
Hi,

We have a requirement where users want an holistic view of the related files not just the Child objects but also the files related to the Account. So that all the information is on the same view or section.

Could you please help us if there us any way possible to add this in the current page setup.

**Comment by douglascayers** [comment]
Hi @MukeshKatochsfdc, for files associated to the Account object (that is, any parent object you're using), please add the standard "Files" related list to the page.

This app provides a "Related Files" component that queries for files related to the child objects, but it doesn't query files for the parent object since that would be redundant of the standard "Files" component.

Here's a screen shot of Lightning App Builder where I'm customizing the Account record page to include the standard "Related List - Single" component to show the Files related list (make sure to add the Files related list to the object's page layout). Below the standard files component, I also have my custom "Related Files" component.

![image](https://user-images.githubusercontent.com/4142577/57978544-79cd3f80-79d5-11e9-9c4b-ac3df4349576.png)
